# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(569, 420)
        self.dear_btn = QtWidgets.QPushButton(parent=Dialog)
        self.dear_btn.setGeometry(QtCore.QRect(10, 20, 131, 23))
        self.dear_btn.setObjectName("dear_btn")
        self.files_list = QtWidgets.QListWidget(parent=Dialog)
        self.files_list.setGeometry(QtCore.QRect(10, 51, 131, 351))
        self.files_list.setObjectName("files_list")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(160, 330, 401, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.left_btn.setObjectName("left_btn")
        self.horizontalLayout.addWidget(self.left_btn)
        self.right_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.right_btn.setObjectName("right_btn")
        self.horizontalLayout.addWidget(self.right_btn)
        self.mirror_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.mirror_btn.setObjectName("mirror_btn")
        self.horizontalLayout.addWidget(self.mirror_btn)
        self.sharp_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.sharp_btn.setObjectName("sharp_btn")
        self.horizontalLayout.addWidget(self.sharp_btn)
        self.bw_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.bw_btn.setObjectName("bw_btn")
        self.horizontalLayout.addWidget(self.bw_btn)
        self.photo_lb = QtWidgets.QLabel(parent=Dialog)
        self.photo_lb.setGeometry(QtCore.QRect(150, 20, 411, 291))
        self.photo_lb.setObjectName("photo_lb")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dear_btn.setText(_translate("Dialog", "Папка"))
        self.left_btn.setText(_translate("Dialog", "Вліво"))
        self.right_btn.setText(_translate("Dialog", "Вправо"))
        self.mirror_btn.setText(_translate("Dialog", "Дзеркало"))
        self.sharp_btn.setText(_translate("Dialog", "Різкізть"))
        self.bw_btn.setText(_translate("Dialog", "Ч / Б"))
        self.photo_lb.setText(_translate("Dialog", "Картинка"))
